# Référentiel enrichi automatiquement
referentiels_multichoix = {
    "certifications_educatives": [
        "Animation et encadrement des jeunes",
        "CAFFA",
        "CAFIPEMF",
        "CAPPEI",
        "Certification DNL",
        "Certification FLS",
        "Certification PIX",
        "Certification linguistique",
        "Concours de l'enseignement secondaire",
        "Direction d'école",
        "Diplôme sportif",
        "Diplôme universitaire (DU)",
        "Enseignement de l'anglais langue étrangère",
        "Enseignement des langues",
        "FLE",
        "Secourisme",
        "Cinéma et audiovisuel",
        "Certification pédagogique spécifique au Maroc",
        "Aucune certification déclarée",
        "**autre (à clarifier)**"
    ],
    "responsabilites_complementaires": [
        "Aucun rôle spécifique",
        "Coordonnateur de discipline",
        "Tuteur de collègue",
        "Fonction de direction",
        "Référent (niveau, numérique, culture, langues, EBEP...)",
        "Mission de formation",
        "Responsable d'activités sportives",
        "Professeur Principal",
        "**mission de formation**",
        "**autre (à clarifier)**"
    ],
    "matieres_niveaux_actuels": [
        "Allemand",
        "Anglais",
        "Arabe",
        "Arts plastiques",
        "Cycle 1",
        "Cycle 2",
        "Cycle 3",
        "Documentation et information",
        "Enseignement scientifique",
        "Espagnol",
        "Français",
        "Histoire-Géographie",
        "Mathématiques",
        "Numérique et sciences informatiques (NSI)",
        "Philosophie",
        "Sciences de la vie et de la Terre (SVT)",
        "Sciences de l’ingénieur",
        "Sciences numériques et technologie (SNT)",
        "Sciences physiques et chimiques",
        "Sciences économiques et sociales (SES)",
        "Vie scolaire",
        "Éducation musicale",
        "Éducation physique et sportive (EPS)",
        "Technologie",
        "**autre (à clarifier)**"
    ],
    "objectifs_outils_numeriques": [
        "Collaboration",
        "Création de contenus",
        "Différenciation pédagogique",
        "Évaluation",
        "Gestion de classe",
        "**autre (à clarifier)**"
    ],
    "competences_dev_formations": [
        "Adapter mon enseignement aux besoins des élèves",
        "Collaborer avec mes collègues et d’autres acteurs éducatifs",
        "Communiquer plus efficacement avec les familles et les élèves",
        "Concevoir des évaluations adaptées et en exploiter les résultats",
        "Développer des stratégies pour favoriser la mémorisation et la compréhension",
        "Encourager l’autonomie et l’engagement des élèves",
        "Innovation pédagogique",
        "Mieux gérer la classe et favoriser un climat scolaire positif",
        "M’engager dans une démarche de formation et d’amélioration continue",
        "Utiliser des outils numériques pour enrichir mon enseignement",
        "Varier mes pratiques pédagogiques pour améliorer l’apprentissage",
        "Accompagnement à l'orientation des élèves",
        "Orientation et mobilité internationale des élèves",
        "Santé et bien-être des élèves",
        "Éducation à la santé et à la sexualité",
        "**autre (à clarifier)**",
        "**m’engager dans une démarche de formation et d’amélioration continue**"
    ],
    "freins_formation_continue": [
        "Aucun frein déclaré",
        "Budget insuffisant",
        "Distance",
        "Manque d'offre",
        "Manque de temps",
        "Pertinence des formations",
        "Politique institutionnelle",
        "**autre (à clarifier)**"
    ],
    "contenus_autoformation": [
        "Centre de ressources éducatives",
        "MOOC",
        "Réseau professionnel",
        "Réseaux sociaux",
        "Site web",
        "articles de recherche",
        "livres",
        "**autre (à clarifier)**"
    ],
    "evaluations_alternatives": [
        "Absence d'évaluation formelle",
        "Auto-évaluation",
        "Oral",
        "Évaluations par groupe",
        "Évaluations par projet",
        "**autre (à clarifier)**"
    ]
}